# https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty

os:
  - linux

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/org/gradoop/

language: java

install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dcheckstyle.skip=true
script: mvn -Dtest=CrossEdgesTest,org.gradoop.flink.model.impl.operators.layouting.*Test -DfailIfNoTests=false -pl gradoop-flink -am test